### ISSUE TITLE
Standard <select> dropdown menu shows on top of the widget

### ISSUE THREAD

**Issue by kachar** [patrickkunka/easydropdown#1]
How to repeat:
1. Open the menu
2. Press 'F' on the keyboard to select February
3. Press Enter key twice

Managed to show the standard menu on Chrome Version 29.0.1547.57 beta on Kubuntu Linux

**Comment by patrickkunka** [comment]
I can't reproduce this in OSX unfortunately, but I've added a couple lines that might help. Let me know!
