### ISSUE TITLE
ln:291 original select not being affected

### ISSUE THREAD

**Issue by builtbylane** [patrickkunka/easydropdown#10]
this code doesn't seem to be working            `self.$select.find('option').prop('selected',false);`

**Comment by builtbylane** [comment]
my html looked like this:

``````
<select> <option val=1 selected>option</option></select>```

I found changing .prop to removeAttr('selected') worked.
``````

**Comment by builtbylane** [comment]
the final code I ended up with...
`self.$select.find('option').removeAttr('selected').eq(selectIndex).attr('selected','selected').parent().trigger('change');`
using jQuery 1.9.1

**Comment by patrickkunka** [comment]
Thanks,

I've integrated this into 2.0.6.
