### ISSUE TITLE
Conflicts with Twitter Bootstrap dropdowns

### ISSUE THREAD

**Issue by laughp** [patrickkunka/easydropdown#13]
Since a class of "dropdown" is used to hook the javascript, it turns any toggle-able drop downs you've made using bootstrap's drop down JS a select box. However, bootstrap only uses their .dropdown class for visual styling.

I would recommend either giving the ability to define your hook name or use a data-attribute rather than a class.

Thanks for the hard work.

**Comment by patrickkunka** [comment]
Use the wrapperClass config option and instantiate via jQuery.
