### ISSUE TITLE
OptGroup seems to be ignore on desktop browsers

### ISSUE THREAD

**Issue by ghost** [patrickkunka/easydropdown#14]
Looks like optgroup is being ignored on desktop browser, works fine on mobile devices. Would be handy if this gets fixed 'opgroups' are incredibly handy for long lists

For example 

``` html
<select>
<optgroup label="group 1">
<option>option 1</option>
<option>option 2</option>
<option>option 3</option>
</optgroup>
<optgroup label="group 2">
<option>option 4</option>
</optgroup>
</select>
```

**Comment by patrickkunka** [comment]
There's currently no support for option groups but I intend to add this in the near future
