### ISSUE TITLE
.easyDropDown('select', index/value) Not Working When Passing a String

### ISSUE THREAD

**Issue by calvinlloyd** [patrickkunka/easydropdown#15]
This method is not working when passing in a string value:

<select class="dropdown">
<option value="a">A</option>
<option value="b">B</option>
<option value="c">C</option>
</select>
$.easyDropDown('select','c');

Does not select the option C.

**Comment by patrickkunka** [comment]
I can't replicate this - it seems to work fine. Make sure your select options have a value attribute e.g:

##### HTML

``` html
<select class="dropdown" id="Test">
    <option value="a">A</option>
    <option value="b">B</option>
    <option value="c">C</option>
</select>
```

##### JS

``` javascript

$('#Test').easyDropDown('select','a'); // selects "A"

$('#Test').easyDropDown('select', 0); // selects "A"
```

**Comment by patrickkunka** [comment]
Oh looks like you're not calling the method correctly. You must refer to the jQuery object of the select. Targeting by ID is the best solution.

**Comment by rambabu** [comment]
Hi ,
The following the select drop down

value ----display value
"16"--13
"17"--18
"15"--7
"13"--APTA
"14"--ext
"18"---test
<select id="ratingvalue" class=""><option value="null">Rating Value</option><option value="16">13</option><option value="17">18</option><option value="15">7</option><option value="13">APTA</option><option value="14">Especialmente Recomendada para la Infancia</option><option value="18">Película X</option></select>

Query:  $("#ratingvalue").easyDropDown('select','17');
The out put generated is :  <option value="16">13</option>(it is selected this option)

This is a bug actually it should select the <option value="17">18</option>

Could you please suggest on this.
