### ISSUE TITLE
Add refresh method

### ISSUE THREAD

**Issue by changalberto** [patrickkunka/easydropdown#22]
When used inside a Modal window. The height of the dropdowns doesn't get properly calculated on hidden modals. Can you add a refresh method to ge triggered once I open up the modal.

Thanks

**Comment by patrickkunka** [comment]
I just pushed v2.1.4 - the dropdown height is now calculated in real time each time a drop down is opened (it was calculated only on instantiation before). Hopefully this also solves the modal issue, if not, I can add a refresh method.

**Comment by changalberto** [comment]
Just tested it. Works great!

**Comment by patrickkunka** [comment]
Awesome, thanks
