### ISSUE TITLE
Make the ".dropdown" class configurable

### ISSUE THREAD

**Issue by thomasfrobieter** [patrickkunka/easydropdown#24]
Or simply rename it to something what´s not used so often, like ".easydropdown". 
You already set the configurable class this.wrapperClass = 'easydropdown', but it seems that the variable is not used in the code (manually use of ".dropdown")?

Thank you :)

**Comment by fidelix** [comment]
This gave me some trouble. Would be nice to have it configurable, or even better, another class altogether
