### ISSUE TITLE
Dynamically update options

### ISSUE THREAD

**Issue by lozcalver** [patrickkunka/easydropdown#25]
The ability to trigger an 'update' event when the list of options has been updated would be a great addition. Similar to http://harvesthq.github.io/chosen/#change-update-events.

Destroying and rebuilding the dropdowns each time with the same options seems to be very inefficient

**Comment by patrickkunka** [comment]
This is definitely a very useful functionality I plan to add in the near future!

**Comment by dejital1** [comment]
I'd like this feature too, is there any chance it is coming anytime soon? Thanks!
