### ISSUE TITLE
Theme CSS breaking Android native select

### ISSUE THREAD

**Issue by lozcalver** [patrickkunka/easydropdown#27]
Hi,

So far I’ve personally tested this on 2.3.3 on a Galaxy S2, though a testing company (working on a site with us) has flagged it as an issue on Galaxy S3, as well as Nexus 10. I’ve also recreated it in Android 4.2.2 on a Nexus 7 (emulated).

The default theme CSS includes `position: absolute` on the `.old` container: https://github.com/patrickkunka/easydropdown/blob/master/themes/easydropdown.css#L75 (all three themes include this). This prevents the ‘native’ select menu from showing when `.focus()` is triggered, if the dropdown is inside an element with `overflow: hidden` or `overflow-x: hidden`. Simply removing the `position: absolute` fixes the issue - though there may be implications for other browsers.

I appreciate this isn’t necessarily an issue with EasyDropDown, but I’m certain that others will encounter this issue in future - worth noting this as an issue for anyone searching :).

More info: https://github.com/jquery/jquery-mobile/issues/2066#issuecomment-1939919

**Comment by Globegitter** [comment]
Good catch. For me I could fix the mobile issue by commenting out `position: absolute` and adding `opacity: 0` so it also won't show on desktops. Perfect.
