### ISSUE TITLE
Its not working in firefox 26

### ISSUE THREAD

**Issue by conair355** [patrickkunka/easydropdown#32]
easydropdown is not workin in firefox 26, is there any fix for it.

**Comment by patrickkunka** [comment]
Please post more information.. behaviour, OS, console error, etc, a link to your project.

http://patrickkunka.github.io/easydropdown/ marketing site appears to work fine in firefox 26 in OS X.

**Comment by conair355** [comment]
Sorry it was my mistake, there was a problem with the browser itself and i reinstalled it.
Now its working fine, thanks.

**Comment by conair355** [comment]
Hi Patrick,

Its working fine now, the problem was with the browser i reinstalled it,
now its working fine.

thanks
