### ISSUE TITLE
Dropdown fails on Firefox 29 (Nightly)

### ISSUE THREAD

**Issue by bkonetzny** [patrickkunka/easydropdown#38]
Firefox 29 will always have support for 'ontouchend' in document, so it will always be detected as isTouch, thus not rendering any options at all. Only workaround is to set nativeTouch=false at the moment.

**Comment by patrickkunka** [comment]
That's good to know - thanks!

**Comment by Mediakik** [comment]
THANK YOU! This was driving me nuts!
