### ISSUE TITLE
Timeout expected when selecting a value with the keyboard

### ISSUE THREAD

**Issue by binairo** [patrickkunka/easydropdown#4]
When trying to select a year for example (in the provided demo), you can type 2002 and that value will be selected. 

On a native select, there is a slight timeout and if you then type 2012, it will select 2012. 

This timeout to reset the search string is missing from easydropdown (I expect that it tries to match 20022012, but I haven't had time to look into the code).

I would be great if this could be added, to provide the most seamless replacement for the native select.

**Comment by patrickkunka** [comment]
Fixed in 2.0.5
