### ISSUE TITLE
.easyDropDown('select', index/value) Not Working When option value and disaply value is different

### ISSUE THREAD

**Issue by rambabu** [patrickkunka/easydropdown#45]
Hi ,
The following the select drop down

value ----display value
"16"--13
"17"--18
"15"--7
"13"--APTA
"14"--ext
"18"---test
<select id="ratingvalue" class=""><option value="null">Rating Value</option><option value="16">13</option><option value="17">18</option><option value="15">7</option><option value="13">APTA</option><option value="14">Especialmente Recomendada para la Infancia</option><option value="18">Película X</option></select>

Query:  $("#ratingvalue").easyDropDown('select','17');
The out put generated is :  <option value="16">13</option>(it is selected this option)

This is a bug actually it should select the <option value="17">18</option>

Could you please suggest on this.

**Comment by aolivieri** [comment]
Same here! It looks like there is a -1 in the .js file that shouldn't be there? If you remove it , it works!

index = self.$select.find('option[value='+index+']').index() - 1;  (remove the -1 from this line)

**Comment by aolivieri** [comment]
BTW, I didn't study the code to see if there is any side effect on this change. Better the author to comment

**Comment by Kylok** [comment]
I also ran into this issue today and removed that -1 to fix it... so +1 for that solution!
