### ISSUE TITLE
AJAX refresh

### ISSUE THREAD

**Issue by juliocorral** [patrickkunka/easydropdown#48]
How could I refresh easyDropdown fields when I refresh then by AJAX?. 
I've three selects (Country-State-City) with easyDropDown, but when I change Country, State and City appears without easyDropDown styles and they loose cutOff property.

Could you help me with this? Thank you in advance and sorry for my terrible English.

**Comment by umgeric** [comment]
I am getting same problem.
I can pay you if you help me.

**Comment by iprignano** [comment]
I had this problem too – fixed it by destroying any rendered dropdown with the .easyDropDown('destroy') method on each AJAX page load. Then, obviously, calling the .easyDropDown() method to re-render them.
