### ISSUE TITLE
Carat Icon not clickable on Android 

### ISSUE THREAD

**Issue by demianh** [patrickkunka/easydropdown#59]
I just found out, that i can't click the carat icon on android (it doesn't open the dropdown). It is just the icon itself, the area around the icon is still clickable.
Work perfectly on iOS and Chrome tough.

Here is how i fixed the problem:

i changed line 84 from:

``` js
self.$carat = $('<span class="carat"/>').appendTo(self.$container);
```

to:

``` js
self.$carat = $('<span class="carat"/>').prependTo(self.$container);
```

and now it also works on Android.

**Comment by robbiegod** [comment]
Windows8, Windows8.1, Windows 8.1 Update - Chrome - I have the same issue in the latest version of Chrome only.  Your fix above fixes the carat issue for me.

This all works fine in Chrome under Windows 7.
