### ISSUE TITLE
Attribute "disabled" does not work

### ISSUE THREAD

**Issue by locito54** [patrickkunka/easydropdown#7]
I was not able to set the attribute "disabled" with jquery for easydropdown selects.

**Comment by phellipeperin** [comment]
I have the same problem here. But i found out a simple solution (using jquery), it follows:

I changed the bindHandlers in 2 different positions (i didnt checkout the touchhandlers).
On self.$container click i changed this:

if(!self.down) {
                            self.open();
                        } else {
                            self.close();
                        };

into this:

if($(self.$select).attr('disabled') == undefined) {
                        if(!self.down) {
                            self.open();
                        } else {
                            self.close();
                        };
                    }

But it will not work if just that, you need to tell the body click not to close your select if you clicked into your select (classes: carat or selected).

Here's my new body click:
$('body').on('click',function(e) {
   var $target = $(e.target), targetClasses = $($target).attr('class');
if(targetClasses == undefined || (targetClasses.indexOf('carat') == -1 && targetClasses.indexOf('selected') == -1)) {
var classNames = "."+self.wrapperClass.split(' ').join('.');
if(!$target.closest(classNames).length && self.down){
self.close();
};
}
});

Sry about code formatting.

Hope it helps.

**Comment by patrickkunka** [comment]
Thanks guys,

I've added support for the disabled attribute on the select element (not the individual options yet) in v2.0.6

I've also added disable/enable methods we can use to programmatically disable the drop-down.
