### ISSUE TITLE
Webpack resolve error

### ISSUE THREAD

**Issue by brandoniffert** [patrickkunka/easydropdown#79]
Currently trying to use with Webpack 4.8.1, using `import easydropdown from 'easydropdown'` I get this error on build

```
ERROR in ./node_modules/easydropdown/dist/Easydropdown/Easydropdown.js
Module not found: Error: Can't resolve '../Config/Config' in ... node_modules/easydropdown/dist/Easydropdown
 @ ./node_modules/easydropdown/dist/Easydropdown/Easydropdown.js 4:15-42
 @ ./node_modules/easydropdown/dist/Easydropdown/factory.js
 @ ./node_modules/easydropdown/dist/index.js
...

ERROR in ./node_modules/easydropdown/dist/State/State.js
Module not found: Error: Can't resolve '../Config/Config' in ... node_modules/easydropdown/dist/State
 @ ./node_modules/easydropdown/dist/State/State.js 4:15-42
 @ ./node_modules/easydropdown/dist/State/StateMapper.js
 @ ./node_modules/easydropdown/dist/Easydropdown/Easydropdown.js
 @ ./node_modules/easydropdown/dist/Easydropdown/factory.js
 @ ./node_modules/easydropdown/dist/index.js
 ...
```

There doesn't appear to be a `Config` directory in `node_modules/easydropdown/dist`

**Comment by ghost** [comment]
Ah thanks - there is a config rule in the .npmignore which appears to case insensitive. Will fix asap.

**Comment by patrickkunka** [comment]
Have now published https://github.com/patrickkunka/easydropdown/releases/tag/4.0.3 - Can you let me know if that fixes it? Thanks!

**Comment by brandoniffert** [comment]
Yes, working now. Thank you for the quick response!

**Comment by patrickkunka** [comment]
No worries - glad you caught this! v4 was just released yesterday and I missed this as I have it symlinked locally. Please let me know if you come across anything else.
