### ISSUE TITLE
Overflow Hidden

### ISSUE THREAD

**Issue by zsteiner** [patrickkunka/easydropdown#8]
When I use easydropdown inside a fixed heigh object (li or td) or at the bottom of section, the  dropdown is hidden, rather than appearing above the content beneath as a native select box would behave. I've tried a few things with absolute positioning and setting z-index via CSS to no avail. Any ideas on how to tweak the CSS of the select box or containing object to prevent this? Attached is the select box inside a table cell. 

![screen shot 2013-09-11 at 1 46 13 pm](https://f.cloud.github.com/assets/4006336/1125070/196c0ff2-1b0a-11e3-92c5-b9d5f92cd298.png)

**Comment by patrickkunka** [comment]
"Overflow: hidden" means "overflow: hidden" hidden unfortunately. We can not replicate the behaviour of the native select dropdown in this case as it technically renders as part of the browser chrome and not part of the DOM, and is therefore not subject to CSS rules. Easydropdown's generated menu is part of the DOM and is therefore subject to CSS rules. If you don't want this to happen, it would be best to find an alternative to using overflow hidden on your containing element.
