### ISSUE TITLE
Bug in Firefox

### ISSUE THREAD

**Issue by Grinyaha** [patrickkunka/easydropdown#80]
![image](https://user-images.githubusercontent.com/5717275/46262444-063ff600-c50a-11e8-8fb2-d8f2dca4b9e5.png)

See screenshot. Firefox 62.0.2

**Comment by patrickkunka** [comment]
Hi there - thanks for pointing this out.

This should be fixed in the latest release https://github.com/patrickkunka/easydropdown/releases/tag/v4.0.4

Please let me know.

**Comment by Grinyaha** [comment]
Thanks.

**Comment by patrickkunka** [comment]
Assuming this is fixed, let me know if otherwise and I'll reopen. Thanks.
