### ISSUE TITLE
npm package has no styles

### ISSUE THREAD

**Issue by irco** [patrickkunka/easydropdown#84]
I added the npm package to my project and pasted the html, added the js initialization and it looked like I had 2 dropdowns. Downloaded the full repo and noticed the demos made references to at least a style sheet (flax.css for example) that are nowhere to be found in the files downloaded by npm.

**Comment by ghost** [comment]
You can find the three themes' stylesheets in the GitHub repo:

https://github.com/patrickkunka/easydropdown/tree/v4/demos/themes

The demos aren't included in the npm package, as I expected that users would need to integrate the css into their existing CSS setup by hand. There's no one size fits all way I could just include the CSS in the distribution. For example - someone might be using SASS, another person might be using CSS modules or styled components.

I was wondering if I need to do a better job of linking to the themes in the Readme, but I've just checked and they are actually linked to in the second paragraph of the Readme.

I'm open to ideas around how to improve this however, so please let me know how you would expect this to be done.

**Comment by irco** [comment]
Thanks for the response I appreciate it! 
I see, I understand the intention is to create the most customizable dropdown but as somebody exploring options the last thing I wanted to see after installing and trying was a broken dropdown I guess I would have expected the bare minimum to make it look like the demo in the npm package ? but maybe I am not like most users and I jump directly at installing and trying myself rather than looking at the demos.

>EasyDropDown comes bundled with three ready-made themes which can be used as a starting point for custom styling.
 
I guess that din't indicate to me that I needed to find the styles myself and or create one but that's my 2 cents not exactly sure whats right or wrong

**Comment by patrickkunka** [comment]
Sure, thanks for the feedback! I'll have a think about how to make this easier.
