### ISSUE TITLE
onSelect callback no longer works when openOnFocus is set

### ISSUE THREAD

**Issue by brandoniffert** [patrickkunka/easydropdown#87]
Hey, in the latest 4.1.0 update you did, it seems that the `onSelect` callback no longer fires when `openOnFocus` is set.

Ex:

```js
easydropdown('select', {
    behavior: {
        openOnFocus: true
    },
    callbacks: {
        onSelect: () => console.log('I never fire')
    }
})
```

**Comment by patrickkunka** [comment]
Apologies - seems like I introduced a few issues. These should be fixed now in https://github.com/patrickkunka/easydropdown/releases/tag/v4.1.1
