### ISSUE TITLE
clampMaxVisibleItems not working with multiline options

### ISSUE THREAD

**Issue by kellydacombe** [patrickkunka/easydropdown#92]
I am not sure whether you support this or not, but the way we are currently using this is that we wrap long items rather than use ellipses.  When a list contains many items all wrapping to two lines, the dropdown does not get properly contained within the viewport even though clampMaxVisibleItems is true.  It appears to be calculating the maxheight based on the height it assumes each item to be, rather than the height they actually are.

**Comment by patrickkunka** [comment]
Hi kelly.

Unfortunately, all items must have the same height in order for any height based features and opening/closing animations to work correctly.

Calculating the height of each item dynamically everytime the dropdown is opened would not be efficient. Additionally, depending on the current scroll offset, or selected item, the height for max visible items could vary significantly.

I hope that makes sense.
