### ISSUE TITLE
Trigger Invalid / Add dynamic classes to edd-head & edd-root

### ISSUE THREAD

**Issue by codeoutin** [patrickkunka/easydropdown#93]
I'm trying to find a way to implement a validation to EasyDropDown that gets triggered by onChange Events. I didn't find a way to toggle 'invalid' classes to edd-head or to edd-root, because EDD seems to rebuild itself after closing the field.

I tried adding a class with jQuery hooked to a onChange Method but the class will be removed as soon as leave the focus of the field / close it. Another method i've tried is setting a custom classname to head with a ternary operator, but it gets ignored on the rebuild.

Is there any way to add and remove classes on edd-head / edd-root or trigger the built-in invalid without submitting the form?

**Comment by patrickkunka** [comment]
Hi @stegerpa - is this solved by the proposal in #94 ?

**Comment by alexmilde** [comment]
yes it will be, cause i work with him - and he brought this up.

**Comment by codeoutin** [comment]
Hi @patrickkunka. Yes the change from @alexmilde fixes my problem. Thank you both!
